### ISSUE TITLE
graphical issues in super smash bros

### ISSUE THREAD

**Issue by carsuki** [rileytestut/N64DeltaCore#1]
i've found that some parts of stages, characters, and the menu show up black and textureless. i'm running a mod in the screenshots, but all of this happens while unmodded as well.

the ones i've found are:

- the tower and moving platform on the peach's castle stage (https://owo.headpat.services/i/bzok.png)
- the torso of mario, and luigi* https://owo.headpat.services/i/hh5d.png
- the menu buttons when configuring a vs match (they're readable when hovered over, though you can faintly see the black part still) https://owo.headpat.services/i/uwjs.png

*mario's torso oddly looks normal in a 4 player match, except when i pause, although the peach's castle parts do not.
playing: https://owo.headpat.services/i/bzok.png
paused: https://owo.headpat.services/i/yqpx.png

**Comment by carsuki** [comment]
forgot to mention, i'm using an iphone 6s on ios 13

**Comment by lonkelle** [comment]
@carsuki Is this still occurring for you?

**Comment by lonkelle** [comment]
Can your port this to the core that is displaying the N64 graphics here if the problem still exists for you: https://github.com/mupen64plus/mupen64plus-video-rice/issues
