### ISSUE TITLE
Random Issues For Smash 64 on Delta

### ISSUE THREAD

**Issue by Benjoby057** [rileytestut/N64DeltaCore#2]
At first was worried it was my ROM but it looks like someone else has the same problem.
1.The ‘Toggle items’ Menu does not appear whatsoever when selecting rules for Versus mode.
2.Certain Menu select buttons are blacked out.
3. Some textures are colored black.

**Comment by Benjoby057** [comment]
Forgot to mention, That was on an IPhone 7 with 2GBs RAM.

**Comment by lonkelle** [comment]
@Benjoby057 Is this still happening on our latest version?

**Comment by lonkelle** [comment]
If the problem still persists on our latest version, I suggest opening a issue here for the core we use: https://github.com/mupen64plus/mupen64plus-video-rice/issues
