### ISSUE TITLE
Graphical Glitches in Starcraft 64

### ISSUE THREAD

**Issue by ILOVEPIE** [rileytestut/N64DeltaCore#3]
There are some issues with graphics in game in Starcraft 64

**Comment by lonkelle** [comment]
This is likely an upstream core issue, discuss it here: https://github.com/mupen64plus/mupen64plus-core/issues

**Comment by lonkelle** [comment]
Graphics can also be discussed here: https://github.com/mupen64plus/mupen64plus-video-rice/issues
