### ISSUE TITLE
No option to enable RAM extension for N64 required for some games.

### ISSUE THREAD

**Issue by ILOVEPIE** [rileytestut/N64DeltaCore#4]
https://en.m.wikipedia.org/wiki/Nintendo_64_accessories#Expansion_Pak_(NUS-007)

Some games need this.

**Comment by lonkelle** [comment]
@ILOVEPIE What games need this - I'll test it?

**Comment by ILOVEPIE** [comment]
Starcraft 64 requires this to run well.

**Comment by lonkelle** [comment]
So without it; it reduces performance but still plays? Okay, I’ll look into this.

**Comment by lonkelle** [comment]
This is actually an upstream core issue - we support the ram expansion pak. 

Open an issue about your problem here https://github.com/mupen64plus/mupen64plus-core/issues or if it's graphical, then here: https://github.com/mupen64plus/mupen64plus-video-rice/issues

**Comment by ILOVEPIE** [comment]
Where is the option to enable it?

**Comment by lonkelle** [comment]
It is enabled by default. Starcraft Even says “Enhanced Pak Detected” on boot.
